/**
* @file MessageIDs.h
*
* Declaration of ids for debug messages.
*
* @author Martin Lötzsch
*/

#pragma once

/**
* IDs for debug messages
*
* To distinguish debug messages, they all have an id.
*/
enum MessageID {
  undefined,
  idProcessBegin,
  idProcessFinished,

  // data (ids should remain constant over code changes, so old log files will still work)
  idImage,
  idJPEGImage,
  idJointData,
  idSensorData,
  idKeyStates,
  idOdometryData,
  idFrameInfo,
  idFilteredJointData,
  idLinePercept,
  idGoalPercept,
  idBallPercept,
  idGroundTruthWorldState,
  idAudioData,
  idCameraMatrix,
  idCameraInfo,
  idImageCoordinateSystem,
  idMotionInfo,
  idRobotPose,
  idBallModel,
  idFilteredSensorData,
  idImageInfo,
  idOrientationData,
  idGameInfo,
  idRobotInfo,
  idOpponentTeamInfo,
  idSideConfidence,
  idDropInPlayer,
  idGroundTruthOdometryData,
  idGroundTruthOrientationData,
  idColorCalibration,
  idOwnTeamInfo,
  idObstacleModel,
  idBehaviorControlOutput,
  idCombinedWorldModel,
  idRobotObstacles,
  idFieldBoundary,
  idRobotHealth,
  idActivationGraph,
  idThumbnail,
  idRobotPercept,
  idStopwatch,
  idLowFrameRateImage,
  idObstacleWheel,
  idBodyContour,
  idReceivedSPLStandardMessages,
  idLineSpots,
  idOdometer,
  idGroundContactState,
  idLocalizationTeamBall,
  idTeammateData,
  idTeammateDataCompressed,
  idTeammateReliability,
  // insert new data ids here
  idCurrentPositionConfidence,
  idCurrentSideConfidence,
  idAverageWalkSpeed,
  idMaxKickDistance,
  idXabslDebugSymbols,
  idXabslDebugMessage,
  idRoleAssignment,
  idBallDirection,
  idDataSPLStandardMessage,    //Test Pablo
  idGoalUnknownPercept,
  idMotionRequest,
  idArmMotionRequest,
  idHeadMotionRequest,
  idBehaviorLEDRequest,
  idBehaviorMotionControl,
  idBehaviorStatus,
  idStrikerDecision,
  idStrikerAvoidance,
  idNearBallTrajectory,
  numOfDataMessageIDs, /**< everything below this does not belong into log files */

  // ids used in team communication
  idNTPHeader = numOfDataMessageIDs,
  idNTPIdentifier,
  idNTPRequest,
  idNTPResponse,
  idRobot,
  idTeammateBallModel,
  idTeammateObstacleModel,
  idTeammateRobotPose,
  idTeammateSideConfidence,
  idTeammateBehaviorStatus,
  idTeammateGoalPercept,
  idTeammateIntention,
  idTeammateGroundTruth,
  idTeammateIsPenalized,
  idTeammateHasGroundContact,
  idTeammateIsUpright,
  idTeammateCombinedWorldModel,
  idReUseMe2, // to be removed
  idTeammateTimeSinceLastGroundContact,
  idTeamCameraHeight,
  idTeammateFieldCoverage,
  idObstacleClusters,
  idWalkTarget,
  idKickTarget,
  idTeam,
  idTeammateBallAge,
  // insert new team comm ids here
  idTeammateRoleAssignment,
  idTeammateRobotObstacles,
  idTeammateStrikerDecision,
  // infrastructure
  idText,
  idDebugRequest,
  idDebugResponse,
  idDebugDataResponse,
  idDebugDataChangeRequest,
  idStreamSpecification,
  idModuleTable,
  idModuleRequest,
  idQueueFillRequest,
  idLogResponse,
  idDrawingManager,
  idDrawingManager3D,
  idDebugImage,
  idDebugJPEGImage,
  idDebugDrawing,
  idDebugDrawing3D,
  idXabslDebugRequest,
  idXabslIntermediateCode,
  idMotionNet,
  idJointRequest,
  idLEDRequest,
  idPlot,
  idStaticPlot,
  idConsole,
  idRobotname,
  idRobotDimensions,
  idJointCalibration,
  idUSRequest,
  idWalkingEngineKick
};
